version: '3'

x-creds: &sasl-security
    KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,BROKER:PLAINTEXT'
    KAFKA_PROCESS_ROLES: 'broker,controller' 
    KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1 
    KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka1:9093,2@kafka2:9093,3@kafka3:9093' 
    KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT' 
    KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER' 
    CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
    KAFKA_LISTENER_NAME_BROKER_SASL_ENABLED_MECHANISMS: PLAIN
    KAFKA_LISTENER_NAME_BROKER_PLAIN_SASL_JAAS_CONFIG: |
      org.apache.kafka.common.security.plain.PlainLoginModule required \
      username="broker" \
      password="broker" \
      user_admin="admin_password"
      user_producer="producer_password" \
      user_consumer="consumer_password";


services:
  ui:
    image: provectuslabs/kafka-ui
    links:
      - kafka1
      - kafka2
      - kafka3
    ports:
      - "5000:8080"
    environment:
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: kafka1:9092
      KAFKA_CLUSTERS_0_NAME: kraft
      #KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema-registry:8081

  kafka1:
    image: confluentinc/cp-kafka:7.7.1
    ports:
      - 9092:9094
    environment:
      <<: *sasl-security
      KAFKA_NODE_ID: 1 
      KAFKA_LISTENERS: 'PLAINTEXT://kafka1:9092,CONTROLLER://kafka1:9093,BROKER://0.0.0.0:9094'  
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka1:9092,BROKER://localhost:9092' 


  kafka2:
    image: confluentinc/cp-kafka:7.7.1
    ports:
      - 9093:9094
    environment:
      <<: *sasl-security
      KAFKA_NODE_ID: 2
      KAFKA_LISTENERS: 'PLAINTEXT://kafka2:9092,CONTROLLER://kafka2:9093,BROKER://0.0.0.0:9094'   
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka2:9092,BROKER://localhost:9093' 

    
  kafka3:
    image: confluentinc/cp-kafka:7.7.1
    ports:
      - 9094:9094
    environment:
      <<: *sasl-security
      KAFKA_NODE_ID: 3
      KAFKA_LISTENERS: 'PLAINTEXT://kafka3:9092,CONTROLLER://kafka3:9093,BROKER://0.0.0.0:9094'   
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka3:9092, BROKER://localhost:9094' 

  # schema-registry:
  #   image: confluentinc/cp-schema-registry:7.2.1
  #   hostname: schema-registry
  #   links:
  #     - kafka1
  #     - kafka2
  #     - kafka3
  #   environment:
  #     SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "PLAINTEXT://kafka1:9092"
  #     SCHEMA_REGISTRY_HOST_NAME: schema-registry